openapi: 3.0.3
info:
  title: Modello Dati FVOE e FVA - OpenAPI 3.0
  version: 1.0.0
  description: |-
   Vengono riportati gli oggetti usati dalle operazioni FVOE e FVA
components:
  schemas:
    StatoFascicoloEnum:
      description: Stato in cui si trova il documento - fare riferimento ai valori contenuti nel file [statoDocumento.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/statoFascicolo.json)
    StatoDocumentoEnum:
      description: Stato in cui si trova il documento - fare riferimento ai valori contenuti nel file [statoDocumento.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/statoDocumento.json)
    StatoRichiestaEnum:
      description: Stato in cui si trova la richiesta di accesso al fvoe - fare riferimento ai valori contenuti nel file [statoRichiesta.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/statoRichiesta.json)
    TipoDocumentoEnum: 
      description: tipologie di documento - fare riferimento ai valori contenuti nel file [tipoDocumento.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/tipoDocumento.json)
    TipoFascicoloEnum:
      description: tipologie di fascicolo - fare riferimento ai valori contenuti nel file [tipoFascicolo.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/tipoFascicolo.json)
    TipoOggettoFascicoloEnum:
      description: tipologie dell''oggetto fascicolo - Identificativo per determinare il tipo di modello dati del Fascicolo- fare riferimento ai valori contenuti nel file [tipoOggettoFascicolo.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/tipoOggettoFascicolo.json)
    TipoAzioneFascicoloEnum:
      description: tipologie delle azioni eseguite sul fascicolo - fare riferimento ai valori contenuti nel file [tipoAzioneFascicolo.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/tipoAzioneFascicolo.json)
    TipoOggettoDocumentoEnum:
      description: tipologie dell''oggetto documento - Identificativo per determinare il tipo di modello dati del Documento- fare riferimento ai valori contenuti nel file [tipoOggettoDocumento.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/tipoOggettoDocumento.json)
    TipoAzioneDocumentoEnum:
      description: tipologie delle azioni eseguite sul fascicolo - fare riferimento ai valori contenuti nel file [tipoAzioneDocumento.json](https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/tipologiche/tipoAzioneDocumento.json)   
    AppaltoType : 
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/AppaltoType'
    FascicoloType: 
      description: Oggetto che riporta i dati del Fascicolo generico
      type: object
      additionalProperties: false
      properties:
        idFascicolo:
          description: identificativo univoco del Fascicolo
          type: string
          example: "507f1f77bcf86cd799439011"
        codiceFascicolo:
          description: codice univoco esterno del Fascicolo . Se tipoFascicolo='FVA' é valorizzato con il codiceAppalto
          type: string
          example: "FAS_202301_45632342"  
        tipoOggetto:
          $ref: '#/components/schemas/TipoOggettoFascicoloEnum' 
        tipoFascicolo:
          $ref: '#/components/schemas/TipoFascicoloEnum'
        stato:
          $ref: '#/components/schemas/StatoFascicoloEnum' 
        azione:
          $ref: '#/components/schemas/TipoAzioneFascicoloEnum'  
        utenteCreazione:
          description: utente di registrazione del fascicolo 
          type: string
          example: "UDI.8909"
        dataCreazione:
          description: data di registrazione del fascicolo (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: "2022-01-23T12:02:05Z"      
    FVOEType:
      allOf: # estende lo schema dati di FascicoloType
        - $ref: '#/components/schemas/FascicoloType'
      description: Oggetto che riporta i dati del FVOE
      type: object
      additionalProperties: false
    FVAType:
      allOf: # estende lo schema dati di FascicoloType
        - $ref: '#/components/schemas/FascicoloType'
      description: Oggetto che riporta i dati del FVA
      type: object
      additionalProperties: false
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoType' 
        documenti:
          description: Lista documenti
          type: array
          items:
            $ref: '#/components/schemas/DocumentoAType'      
    DocumentoType:
      description: Oggetto che riporta i dati del Documento
      type: object
      additionalProperties: false
      properties:
        idDocument:
          description: identificativo univoco del documento
          type: string
          example: "507f1f77bcf86cd799439011"
        tipoOggetto:
          $ref: '#/components/schemas/TipoOggettoDocumentoEnum'
        tipoDcumento:
          $ref: '#/components/schemas/TipoDocumentoEnum'
        statoDocumento:
          $ref: '#/components/schemas/StatoDocumentoEnum'
        dataInserimento:
          description: data di inserimento del documento (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        dataEmissione:
          description: data di emissione del documento (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        dataFineValidita:
          description: data fine validità del documento(A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        numeroProtocollo:
          description: numero di registrazione del documento
          type: string
          example: '2342344342'
        dataProtocollo:
          description: data di registrazione del documento  (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        azione:
          $ref: '#/components/schemas/TipoAzioneDocumentoEnum'   
        utenteCreazione:
          description: utente di registrazione del documento
          type: string
          example: "UDI.8909"  
        dataCreazione:
          description: data di registrazione del documento  (A datetime specified by RF3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z'        
    DocumentoOEType:
      description: Oggetto che riporta i dati del Documento dell'OE
      allOf: # estende lo schema dati di DocumentoType
        - $ref: '#/components/schemas/DocumentoType'
      type: object
      additionalProperties: false
    DocumentoAType:
      description: Oggetto che riporta i dati del Documento dell'Appalto
      allOf: 
        - $ref: '#/components/schemas/DocumentoType' # estende lo schema dati di DocumentoType
        # TBD POSSIBILI PROBLEMI APPLICATIVI LATO CLIENT- $ref: '#/components/schemas/DocumentoOEType' #estende lo schema dati di DocumentoOE perché potrebbe essere un Documento dell' Operatore Economico
      type: object
      additionalProperties: false
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoType'
        fascicoliA:
          type: array
          items:
            $ref: '#/components/schemas/FVAType'
        datiAggiuntivi:
          description: dati aggiuntivi definiti dal Sistema proprietario del documento. Definiti in JSON
          type: string
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"       
    ContentDocumentType:
      description: Oggetto che riporta il contenuto del
      type: object
      additionalProperties: false
    AutorizzazioneAccessoType:
      description: Oggetto che riporta tutti i dati della Pianificazione
      type: object
      additionalProperties: false
    RichiestaAccessoType:
      description: Oggetto che riporta i dati della Richiesta di Accesso
      type: object
      additionalProperties: false
    AnagraficaType:
      description: Oggetto generico dell'anagrafica
      type: object
      additionalProperties: false
    AnagraficaOEType:
      allOf: # estende la classe AnagraficaType
        - $ref: '#/components/schemas/AnagraficaType'
      description: Oggetto specifico dell'anagrafica dell'OE
      type: object
      additionalProperties: false
