openapi: 3.0
info:
  title: Modello Schede Dati - OpenAPI 3.0
  version: 1.0.0
components:
  schemas:
    StatoSchedaEnum:
      type: string
      minimum: 1
      enum: []   
      description: >
        stato- Stato in cui si trova la Scheda:
    TipoSchedaEnum :
      type: string
      minimum: 1
      enum: ['']
      description: >
            scheda- Le possibili schede:
    SchedaType:
      description: Scheda generica definita dal contesto in cui si trova l'appalto
      type: object
      additionalProperties: false
