openapi: 3.0.3
info:
  title: Modello Dati FVOE e FVA - OpenAPI 3.0
  version: 1.0.0
  description: |-
   Vengono riportati gli oggetti usati dalle operazioni FVOE e FVA
components:
  schemas:
    StatoAutorizzazioneEnum:  
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/StatoAutorizzazioneEnum'
    StatoFascicoloEnum:
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/StatoFascicoloEnum'
    StatoDocumentoEnum:
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/StatoDocumentoEnum'
    TipoDocumentoEnum: 
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/TipoDocumentoEnum'
    TipoFascicoloEnum:
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/TipoFascicoloEnum'
    TipoOggettoFascicoloEnum:
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/TipoOggettoFascicoloEnum'
    TipoAzioneFascicoloEnum:
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/TipoAzioneFascicoloEnum'
    TipoAzioneDocumentoEnum:
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/TipoAzioneDocumentoEnum'
    AppaltoType : 
      $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/AppaltoType'
    FascicoloType: 
      description: Oggetto che riporta i dati del Fascicolo generico
      type: object
      additionalProperties: false
      properties:
        idFascicolo:
          description: identificativo univoco del Fascicolo
          type: string
          example: "507f1f77bcf86cd799439011"
        codiceFascicolo:
          description: codice univoco esterno del Fascicolo . Se tipoFascicolo='FVA' é valorizzato con il codiceAppalto
          type: string
          example: "FAS_202301_45632342"  
        tipoOggetto:
          $ref: '#/components/schemas/TipoOggettoFascicoloEnum' 
        tipoFascicolo:
          $ref: '#/components/schemas/TipoFascicoloEnum'
        stato:
          $ref: '#/components/schemas/StatoFascicoloEnum' 
        azione:
          $ref: '#/components/schemas/TipoAzioneFascicoloEnum'  
        utenteCreazione:
          description: utente di registrazione del fascicolo 
          type: string
          example: "UDI.8909"
        dataCreazione:
          description: data di registrazione del fascicolo (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: "2022-01-23T12:02:05Z"
        numDocumenti:
            description: numero della pagina da visualizzare.
            type: integer
            format: int32
            minimum: 10
            default: 0
        documenti:
          description: Lista documenti
          type: array
          items:
            $ref: '#/components/schemas/DocumentoType'    
        numSottoFascicoli:
            description: numero della pagina da visualizzare.
            type: integer
            format: int32
            minimum: 10
            default: 0
        SottoFascicoli:
          description: Lista Sotto Fascicoli
          type: array
          items:
            $ref: '#/components/schemas/FascicoloType' 
        datiAggiuntivi:
          description: dati aggiuntivi del Fascicolo. Definiti in JSON
          type: string
          example: "{appalto : {idAppalto: 35553535K},
                    	schede:[{
                    		id:566eb3c704c7b31facbb0007,
                    		nome:P1.10,
                    		dataInserimento:2015-05-28T14:07:17Z,
                    		idAppalto:35553535K,
                        espd:54495ad94c934721ede76d90,
		                    eform:566eb3c704c7b31facbb0007}]}"    
    FVOEType:
      allOf: # estende lo schema dati di FascicoloType
        - $ref: '#/components/schemas/FascicoloType'
      description: Oggetto che riporta i dati del FVOE
      type: object
      additionalProperties: false
      properties:
        anagraficaOE: 
          $ref: '#/components/schemas/AnagraficaOEType'
    FVAType:
      allOf: # estende lo schema dati di FascicoloType
        - $ref: '#/components/schemas/FascicoloType'
      description: Oggetto che riporta i dati del FVA
      type: object
      additionalProperties: false
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoType'
    DocumentoType:
      description: Oggetto che riporta i dati del Documento
      type: object
      additionalProperties: false
      properties:
        idDocumento:
          description: identificativo univoco del documento
          type: string
          example: "507f1f77bcf86cd799439011"
        tipo:
          $ref: '#/components/schemas/TipoDocumentoEnum'
        stato:
          $ref: '#/components/schemas/StatoDocumentoEnum'
        dataInserimento:
          description: data di inserimento del documento (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        dataEmissione:
          description: data di emissione del documento (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        dataFineValidita:
          description: data fine validità del documento(A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        numeroProtocollo:
          description: numero di registrazione del documento
          type: string
          example: '2342344342'
        dataProtocollo:
          description: data di registrazione del documento  (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        azione:
          $ref: '#/components/schemas/TipoAzioneDocumentoEnum'   
        utenteCreazione:
          description: utente di registrazione del documento
          type: string
          example: "UDI.8909"  
        dataCreazione:
          description: data di registrazione del documento  (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        datiAggiuntivi:
          description: dati aggiuntivi definiti dal Sistema proprietario del documento. Definiti in JSON
          type: string
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        fascicoli: 
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/FascicoloType'
    ContentDocumentType:
      description: Oggetto che riporta il contenuto del
      type: object
      additionalProperties: false
      properties:
        nomefile:
          description: nomeFile originale
          type: string
          example: "Allegato5674.pdf"
        estensione:
          description: estensione file
          type: string
          example: "PDF"
        dimensione:
          description: grandezza del documento
          type: string
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        contenuto:
          description: Contenuto in formato Binario del documento
          type: string
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
    AutorizzazioneAccessoType:
      description: Oggetto che descrive l'autorizzazione concessa dal' OE verso il SA per poter accedere al proprio FVOE
      type: object
      additionalProperties: false
      required:
        - dataInizio
        - stato
      properties:
        idAutorizzazione:
            description: identificativo univoco dell'Autorizzazione restituito da ANAC.
            type: string
            format: uui
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        anagraficaOE:
          $ref: '#/components/schemas/AnagraficaOEType'
        dataInizio:
          description: data inizio autorizzazione (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z'
        dataFine:
          description: data fine autorizzazione (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z'  
        stato:
          $ref: '#/components/schemas/StatoAutorizzazioneEnum'
        motivo:
          description: motivo dell''autorizzazione o del rifiuto
          type: string
          maxLength: 255
        autorizzante: 
          $ref: '#/components/schemas/AnagraficaOEType'
        richiestaAccesso:
          $ref: '#/components/schemas/RichiestaAccessoType' 
    RichiestaAccessoType:
      description: Oggetto che riporta i dati della Richiesta di Accesso
      type: object
      additionalProperties: false
      required:
        - anagraficaOE
        - appalto
        - richiedente
      properties:
        idRichiesta:
            description: identificativo univoco della richiesta restituito da ANAC.
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        dataInizioAutorizzazione:
          description: data richiesta dal SA per accedere al FVOE (A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z' 
        dataFineAutorizzazione:
          description: data richiesta dal SA come termine all'autorizzaione al FVOE(A datetime specified by ISO 8601 as profiled by RFC 3339)
          type: string
          format: datetime
          example: '2022-01-23T12:02:05Z'
        anagraficaOE: 
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/AnagraficaOEType' 
        appalto:
          $ref: '#/components/schemas/AppaltoType' 
        richiedente: 
          $ref: '#/components/schemas/AnagraficaSAType'   
        autorizzazioni:
          type: array
          items:
            $ref: '#/components/schemas/AutorizzazioneAccessoType'
    AnagraficaType:
      description: Oggetto generico dell'anagrafica
      type: object
      additionalProperties: false
      properties:
        codice:
          description: codice identificativo anagrafica. Se 'SA' é il codiceAUSA se 'OE' é il CF/PIVA
          type: string
          example: xcdsd5#3346
    AnagraficaOEType:
      allOf: # estende la classe AnagraficaType
        - $ref: '#/components/schemas/AnagraficaType'
      description: Oggetto specifico dell'anagrafica dell'OE
      type: object
      additionalProperties: false
    AnagraficaSAType:
      allOf: # estende la classe AnagraficaType
        - $ref: '#/components/schemas/AnagraficaType'
      description: Oggetto specifico dell'anagrafica dell'SA
      type: object
      additionalProperties: false
