openapi: 3.0.3
info:
  title: Modello Dati NPA - OpenAPI 3.0
  version: 1.0.0
components:
    schemas:
      SchedaType:
        description: Scheda generica definita dal contesto in cui si trova l'appalto
        type: object
        additionalProperties: false
        properties:
          _idScheda:
            $ref: '#/components/schemas/IdSchedaType'
          _idStatoScheda:
            description: identificativo dello stato della Scheda 
            type: string
            example: '1'
          _origineScheda:
            description: origine Scheda 
            type: string
            example: ''          
          _versione:
            description: versione della scheda. necessaria al motore interno ANAC.
            type: string
            example: '01.00.00'
          _dataCreazione:
            description: data creazione della pianificazione (A datetime specified by RF3339)
            type: string
            format: datetime
            example: '2022-01-23T12:02:05Z'          
      SchedaPianificazioneType:
        description: Scheda generica definita dal contesto in cui si trova l'appalto
        allOf: # estende il modello dati SchedaType
          - $ref: '#/components/schemas/SchedaType'       
        type: object
        additionalProperties: false
        oneOf:
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.10Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.11.yaml#/components/schemas/SchedaP1.11Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.12.yaml#/components/schemas/SchedaP1.12Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.13.yaml#/components/schemas/SchedaP1.13Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.14.yaml#/components/schemas/SchedaP1.14Type'
      SchedaComunicaAppaltoType:
        description: Scheda generica definita dal contesto in cui si trova l'appalto
        type: object
        additionalProperties: false
        properties:
          _idScheda:
            $ref: '#/components/schemas/IdSchedaType'
          _idStatoScheda:
            description: identificativo dello stato della Scheda 
            type: string
            example: '1'
          _origineScheda:
            description: origine Scheda 
            type: string
            example: ''          
          _versione:
            description: versione della scheda. necessaria al motore interno ANAC.
            type: string
            example: '01.00.00'
          _dataCreazione:
            description: data creazione della pianificazione (A datetime specified by RF3339)
            type: string
            format: datetime
            example: '2022-01-23T12:02:05Z'
        oneOf:
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.10Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.11Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.12Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.13Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.14Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.16Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.17Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.18Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.19Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.20Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.21Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.23Type' 
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP1.24Type'        
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.10Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.11Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.12Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.13Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.14Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.16Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.17Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.18Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.19Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.20Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.21Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.23Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP2.24Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP3.1Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP3.2Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP3.3Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP3.5Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP4.1Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP4.2Type'
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaP5Type'   
      SchedaPostPubblicazioneType:
        description: Scheda generica definita dal contesto in cui si trova l'appalto
        type: object
        additionalProperties: false
        properties:
          _idScheda:
            $ref: '#/components/schemas/IdSchedaType'
          _idStatoScheda:
            description: identificativo dello stato della Scheda 
            type: string
            example: '1'
          _origineScheda:
            description: origine Scheda 
            type: string
            example: ''          
          _versione:
            description: versione della scheda. necessaria al motore interno ANAC.
            type: string
            example: '01.00.00'
          _dataCreazione:
            description: data creazione della pianificazione (A datetime specified by RF3339)
            type: string
            format: datetime
            example: '2022-01-23T12:02:05Z'
        oneOf:
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml#/components/schemas/SchedaCL1Type'
      IdSchedaType:
        description: Identificativo univoco della Scheda restituito da ANAC in fase di creazione Scheda
        type: string
        format: uuid
        example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6" 
      StatoDocumentoEnum:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/StatoDocumentoEnum'
      StatoRichiestaType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/StatoRichiestaType'
      TipoDocumentoEnum: 
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/TipoDocumentoEnum'
      AnagraficaOEType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/AnagraficaOEType' 
      FVOEType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/FVOEType' 
      FVAType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/FVAType'
      DocumentoType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/DocumentoType'
      DocumentoOEType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/DocumentoOEType'
      DocumentoAType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/DocumentoAType'
      ContentDocumentType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/ContentDocumentType' 
      AutorizzazioneAccessoType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/AutorizzazioneAccessoType' 
      RichiestaAccessoType:
        $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-fvoe-fva.yaml#/components/schemas/RichiestaAccessoType'
      StatoSchedaEnum:
        type: string
        minimum: 1
        enum: []
        description: >
            statoScheda - Stato della Scheda
      TipoSchedaEnum:
        type: string
        minimum: 1
        enum: []
        description: >
            tipoScheda - Tipologia di Scheda
      TipoFunzioneEnum:
        type: string
        minimum: 1
        enum: []
        description: >
            tipoFunzione - Tipologia di Funzione associabili ad un Soggetto
      TipoOperazioneEnum :
        type: string
        minimum: 1
        enum: [ ]
        description: >
            tipoOperazione - Tipo Operazione di cui si richiedere l'esito dell'operazione
      TipoPianoEnum:
        type: string
        minimum: 1
        enum: []
        description: >
            tipoOperazione - Tipo Operazione di cui si richiedere l'esito dell'operazione
      TipoAzioneAvvisoEnum:
        description: azione dell'avviso
        type: string
        minimum: 1
        enum: []
      TipoAvvisoEnum:
        description: Tipologie di avvisi 
        type: string
        minimum: 1
        enum: []
      TipoRuoloEnum:
        type: string
        minimum: 1
        enum: [] 
      StatoPianoEnum:  
        type: string
        minimum: 1
        enum: []
      StatoAppaltoEnum: 
        type: string
        minimum: 1
        enum: []
        description: >
          stato- Stato in cui si trova la Appalto
      StatoAvvisoEnum:
        type: string
        minimum: 1
        enum: []
        description: >
          stato - Stato in cui si trova l'avviso
      StatoLottoEnum:
        type: string
        minimum: 1
        enum: []
        description: >
            stato- Stato in cui si trova il lotto:
      CigType:
        description: coppia progressivoLotto-CIG
        type: object
        additionalProperties: false
      AnagraficaType:
        description: oggetto generico dell'anagrafica
        type: object
        additionalProperties: false
      RuoloType:
        description: ruolo
        type: object
        additionalProperties: false
      AnagraficaSoggettoType:
        allOf: # estende la classe AnagraficaType
          - $ref: '#/components/schemas/AnagraficaType'
        description: Oggetto specifico dell'anagrafica
        type: object
        additionalProperties: false
      LottoType:
        description: Oggetto che riporta tutti i dati del lotto
        type: object
        additionalProperties: false
      AppaltoType:
        description: Oggetto che riporta tutti i dati dell'Appalto
        type: object
        additionalProperties: false
      AvvisoType:
        description: Oggetto che riporta i dati dell'Avviso
        type: object
        additionalProperties: false
        properties:
          idAvviso:
            description: identificativo univoco dell'Avviso generato da ANAC
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
          scheda:
            description: Scheda generica definita dal contesto in cui si trova l'appalto
            allOf: # estende il modello dati SchedaType
              - $ref: '#/components/schemas/SchedaType'       
            type: object
            additionalProperties: false
            oneOf:
              - $ref: '#/components/schemas/SchedaPianificazioneType'
              - $ref: '#/components/schemas/SchedaComunicaAppaltoType'
              - $ref: '#/components/schemas/SchedaPostPubblicazioneType'
        required:
          - idAvviso
      PianoType:
        description: Oggetto che riporta tutti i dati della Pianificazione
        type: object
        additionalProperties: false
      PaginazioneType:
        description: Oggetto per la paginazione dei risultati
        type: object
        additionalProperties: false
        properties:
          totRows: 
            description: Numero totale di record risultante dalla ricerca
            type: integer
            format: int32
          totPages: 
            description: Numero totale di pagine risultanti dalla ricerca
            type: integer
            format: int32      
          currentPage: 
            description: Numero di pagina corrente
            type: integer
            format: int32
          elementPage:
            description: Numero di elementi per pagina
            type: integer
            format: int32
      DatiAppaltoType:
        description: Oggetto Complesso che riporta tutti i dati dell'appalto
        type: object
        additionalProperties: false
        properties:
          idAppalto:
            description: identificativo univoco dell'Appalto definito da ANAC. Restituito dall'operazione di creazione Appalto. (A UUID specified by RFC4122)
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
          scheda:
            $ref: '#/components/schemas/SchedaComunicaAppaltoType'
        required:
          - idAppalto
      DatiSchedaType:
        description: Oggetto Complesso che riporta tutti i dati delle schede
        allOf: # estende il modello dati SchedaType
              - $ref: '#/components/schemas/SchedaPostPubblicazioneType'
      DatiPianoType :
        description: Oggetto Complesso che riporta tutti i dati dell'appalto 
        type: object
        additionalProperties: false
        properties:
          idPianificazione:
            description: identificativo univoco della Pianificazione definito da ANAC. Restituito dall'operazione di creazione Pianificazione. (A UUID specified by RFC4122)
          scheda:
            $ref: '#/components/schemas/SchedaPianificazioneType' 
        required:
          - idPianificazione
      EsitoOperazioneType:
        type: object
        additionalProperties: false
        required:  # List the required properties here
          - codice
          - descrizione
        properties:
          codice: 
            description: codice dell'esito dell'operazione
            type: string
            example: '01'
          descrizione:
            description: descrizione dell'esito dell'operazione
            type: string
            example: 'AVVISO PUBBLICATO'
          dettaglio:
            description: descrizione dettagliata dell'esito dell'operazione
            type: string
