openapi: 3.0.0
info:
  title: Modello Dati - Scheda A2.35 - Scheda relativa all'aggiudicazione sottosoglia senza invio al TED - Avviso di aggiudicazione di una concessione — direttiva sulle concessioni, regime alleggerito. Articolo 32, paragrafo 2 (riferimento all’allegato VIII), della direttiva 2014/23/UE.
  version: 1.0.0
components:
  schemas:
    AggiudicatarioA2.35Type:
      description: Dati dell'aggiudicatario
      type: object
      additionalProperties: false 
      properties:
        cf:
          description: codice fiscale del soggetto interessato
          type: string
        denominazione: 
          description: denominazione del soggetto interessato
          type: string  
        ruolo: 
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/RuoloOEEnum'
        tipo: 
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/TipoOEEnum'
        idGruppo:
          description: id gruppo
          type: string   
    AnacFormA2.35DatiBaseType:
      description: Oggetto che contiene gli oggetti comuni con il TED relativi alle aggiudicazioni sottosoglia - Avviso di aggiudicazione di un appalto — direttiva settoriale, regime alleggerito. Articolo 92, paragrafo 2, della direttiva 2014/25/UE.
      allOf: # estende la classe AnacFormA2DatiBaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormA2DatiBaseType'       
      type: object
      additionalProperties: false
      properties:
        datiBaseAggiudicazioneSubappalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneSubappaltoType'  
    AnacFormA2.35Type:
      description: Contiene tutti i dati relativi all'aggiudicazione sottosoglia senza invio al TED - Avviso di aggiudicazione di una concessione — direttiva sulle concessioni, regime alleggerito. Articolo 32, paragrafo 2 (riferimento all’allegato VIII), della direttiva 2014/23/UE.
      allOf: 
      - $ref: '#/components/schemas/AnacFormA2.35DatiBaseType'
      type: object
      required: [aggiudicatari]
      additionalProperties: false
      properties:
        aggiudicatari:
          description: Dati degli aggiudicatari
          type: array
          items: 
            $ref: '#/components/schemas/AggiudicatarioA2.35Type'
        incaricati:
          description: dati degli incaricati
          type: array
          items: 
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/IncaricatoType'   
        quadroEconomicoConcessioni:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoConcessioniType'     
    SchedaA2.35Type:
      description: Scheda relativa all'aggiudicazione sottosoglia senza invio al TED - Avviso di aggiudicazione di una concessione — direttiva sulle concessioni, regime alleggerito. Articolo 32, paragrafo 2 (riferimento all’allegato VIII), della direttiva 2014/23/UE.
      type: object
      required: [anacFormA2]
      additionalProperties: false
      properties:
        anacFormA2:
          $ref: '#/components/schemas/AnacFormA2.35Type'           