openapi: 3.0.0
info:
  title: Modello Dati - Scheda P3.2 - Scheda di pubblicazione relativa ai contratti esclusi in Concessione o Contratti esclusi in Concessione con la tecnica dell'AQ.
  version: 1.0.0
components:
  schemas:
    LottoP3.2Type:
      description: Oggetto che riporta i dati del lotto all'interno della fase di pubblicazione sopra soglia e sotto soglia
      allOf: # estende la classe LottoP3BaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP3BaseType'      
      type: object
      required: [afferenteInvestimentiPNRR,opzioni/rinnovi,motivoEsclusioneConcessione]
      additionalProperties: false
      properties:
        motivoEsclusioneConcessione: 
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoEsclusioneConcessioneEnum'  
        datiBase:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoType' 
        datiBaseCPV:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType'
        datiBaseContratto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseContrattoType'   
        datiBaseAggiudicazione:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneP3ContrattiEsclusiType'  
        datiBaseAggiuntivi:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiuntiviType'  
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiTerminiInvioType'          
    AppaltoP3.2Type:
      description: Oggetto che riporta i dati dell'appalto relativi ai contratti esclusi in Concessione o Contratti esclusi in Concessione con la tecnica dell'AQ
      allOf: # estende la classe AppaltoP3BaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP3BaseType'      
      type: object
      #required: []
      additionalProperties: false
      properties:
        datiBase:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoType'    
        datiBaseProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraP3ContrattiEsclusiType'  
        datiBaseStrumentiProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseStrumentiProceduraType'          
    AnacFormP3.2Type:
      description: Contiene i dati relativi ai contratti esclusi in Concessione o Contratti esclusi in Concessione con la tecnica dell'AQ
      type: object
      required: [categoria, appalto,lotti]
      additionalProperties: false
      properties:  
        appalto: 
          $ref: '#/components/schemas/AppaltoP3.2Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP3.2Type'           
        stazioniAppaltanti:
          description: Dati relativi alle stazioni appaltanti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/StazioneAppaltanteType'    
    SchedaP3.2Type:
      description: Scheda di pubblicazione relativa ai contratti esclusi in Concessione o Contratti esclusi in Concessione con la tecnica dell'AQ
      type: object
      required: [anacForm, anacFormP3DatiBase]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP3.2Type' 
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'        