openapi: 3.0.0
info:
  title: Modello Dati - Scheda A3.1 - Scheda di aggiudicazione relativa ai Contratti esclusi (generale o di tipo accordo quadro)
  version: 1.0.0
components:
  schemas:
    AppaltoA3.1Type:
      type: object
      additionalProperties: false
      properties:  
        datiBaseAggiudicazioneSubappalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneSubappaltoType'      
    AggiudicazioneA3.1Type:
      description: Oggetto che riporta i dati inerenti la fase di aggiudicazione
      type: object
      additionalProperties: false
      properties: 
        cig:
          description: codice identificativo lotto
          type: string
          example: 
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string      
        modalitaRiaggiudicazioneAffidamento:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModalitaRiaggiudicazioneAffidamentoEnum'
        numeroOfferteAmmesse:
          description: numero di offerte ammesse
          type: string
          format: integer 
        valoreSogliaAnomalia:
          description: Valore soglia anomalia
          type: string
        nOfferte:
          description: N.offerte >= soglia anomalia
          type: string
          format: integer
        nImpreseEscluseAutomaticamente: 
          description: Numero imprese escluse automaticamente
          type: string
          format: integer
        nImpreseEscluseInsufficientiGiustificazioni: 
          description: Numero imprese escluse per insufficienti giustificazioni
          type: string
          format: integer           
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoType' 
        offertePresentate:
          description: Dati degli aggiudicatari
          type: array
          items: 
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/OfferteType'          
        datiBaseAggiudicazioneAppalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneAppaltoA3.1Type'     
        datiBaseRisultatoProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseRisultatoProceduraType'          
        datiBaseSottomissioniRicevute:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSottomissioniRicevuteType'  
    AnacFormA3.1Type:
      description: Contiene tutti i dati relativi all'aggiudicazione per i contratti esclusi generali
      type: object
      required: [appalto,aggiudicazioni]
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoA3.1Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneA3.1Type' 
    SchedaA3.1Type:
      description: Scheda di aggiudicazione relativa ai contratti esclusi generali
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA3.1Type'