openapi: 3.0.0
info:
  title: Modello Dati - Scheda M1_39 - Scheda relativa alle modifiche contrattuali con invio al TED - Avviso di modifica di un appalto — direttiva settoriale - Articolo 89, paragrafo 1, della direttiva 2014/25/UE con invio di eform39.
  version: 1.0.0
components:
  schemas:
    AnacFormM1_39Type:
      description: Contiene tutti i dati relativi alle modifiche contrattuali con invio al TED - Avviso di modifica di un appalto — direttiva settoriale - Articolo 89, paragrafo 1, della direttiva 2014/25/UE
      type: object
      required: [modificheContrattuali]
      additionalProperties: false
      properties:
        modificheContrattuali:
         type: array
         items:          
          $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattualeType'  
    SchedaM1_39Type:
      description: Scheda relativa alle modifiche contrattuali con invio al TED - Avviso di modifica di un appalto — direttiva settoriale - Articolo 89, paragrafo 1, della direttiva 2014/25/UE con invio di eform39.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormM1_39Type'
        eform:
          $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'           