openapi: 3.0.0
info:
  title: Modello Dati - Scheda IR1 - Scheda di istanza di recesso.
  version: 1.0.0
components:
  schemas:
    EsecuzioneType:
      description: Oggetto che riporta i dati di istanza di recesso.
      type: object
      additionalProperties: false
    AnacFormIR1Type:
      description: Contiene tutti i dati di istanza di recesso
      type: object
      additionalProperties: false
      properties:  
        esecuzione:
          $ref: '#/components/schemas/EsecuzioneType'
    SchedaIR1Type:
      description: Scheda di istanza di recesso
      type: object
      required: [anacFormIR1]
      additionalProperties: false
      properties:
        anacFormIR1:
          $ref: '#/components/schemas/AnacFormIR1Type'