openapi: 3.0.0
info:
  title: Modello Dati - Scheda NAG1 - Scheda di mancata aggiudicazione della gara - procedura europea, con invio al TED.
  version: 1.0.0
components:
  schemas:
    SchedaNAG1Type:
      description: Scheda di mancata aggiudicazione della gara - procedura europea.
      type: object
      required: [eform]
      additionalProperties: false
      properties:
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType' 