openapi: 3.0.0
info:
  title: Modello Dati - Scheda SU1 - Scheda di richiesta di subappalto.
  version: 1.0.0
components:
  schemas:
    SubappaltoType:
      description: Dati relativi ai subappalti
      type: object
      required: [codContratto,codiceFiscaleDitta,impresaEstera,importoPresunto]
      additionalProperties: false
      properties:    
        codContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string 
        codiceFiscaleDitta:
          description: Codice fiscale ditta subappaltatrice
          type: string
        impresaEstera:
          description: Impresa estera?
          type: boolean
        codiceFiscaleAggiudicatario:
          description: Codice fiscale ditta aggiudicatrice nel caso di aggiudicatari multipli
          type: string          
        oggetto:
          description: Lavoro/Servizio/Fornitura subappalto
          type: string
        importoPresunto:
          description: Importo presunto Lavoro/ Servizio/Fornitura, subappalto
          type: number
          format: double
        categoria:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum' 
        cpv:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CPVEnum'   
    AnacFormSU1Type:
      description: Contiene tutti i dati relativi alla scheda di Richiesta di Subappalto
      type: object
      required: [subappalti]
      additionalProperties: false
      properties: 
        subappalti:
          type: array
          items:
            $ref: '#/components/schemas/SubappaltoType'
    SchedaSU1Type:
      description: Scheda di richiesta di subappalto
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSU1Type'