openapi: 3.0.0
info:
  title: Modello Dati - Scheda S2 - La scheda è valida sia per raccogliere l'elenco dei partecipanti che hanno presentato offerta e degli invitati che non hanno presentato offerta per le procedure a doppia fase, che l'elenco dei partecipanti per le procedure a fase unica.
  version: 1.0.0
components:
  schemas:
    InvitatiType:
      description: Elenco di soggetti invitati che non hanno presentato offerta.
      type: object
      additionalProperties: false
      properties: 
        invitati:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/InvitatoType'  
    PartecipantiType:
      description: Elenco di soggetti che hanno presentato offerta.
      type: object
      additionalProperties: false
      properties: 
        partecipanti:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/PartecipanteType'              
    SchedaS2Type:
      description: Elenco di soggetti che hanno presentato offerta e di ulteriori invitati che non hanno presentato offerta.
      type: object
      additionalProperties: false
      required: [anacForm]
      properties:
        anacForm:
          type: object
          additionalProperties: false
          required: [cig, dataScadenzaPresentazioneOfferta]
          properties:
            cig:
              description: codice identificativo lotto
              type: string
            invitatiCheNonHannoPresentatoOfferta:
              description: Dati relativi ai soggetti invitati che non hanno presentato offerta
              type: array
              items:
                $ref: '#/components/schemas/InvitatiType'
            partecipanti:
              description: Dati relativi ai partecipanti
              type: array
              items:          
                $ref: '#/components/schemas/PartecipantiType'              
            dataInvito: 
              description: Data della lettera di invito
              type: string
              format: datetime
            dataScadenzaPresentazioneOfferta: 
              description: Data della scadenza di presentazione dell'offerta
              type: string
              format: datetime            