openapi: 3.0.0
info:
  title: Modello Dati - Scheda NAG2 - Scheda di mancata aggiudicazione della gara - procedura nazionale
  version: 1.0.0
components:
  schemas:
    AnacFormNAG2DatiBaseType:
      description: Oggetto che contiene gli oggetti comuni con il TED relativi alla mancata aggiudicazione della gara - procedura nazionale
      type: object
      additionalProperties: false
      properties:
        datiBaseRisultatoProceduraNAG2:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseRisultatoProceduraNAG2Type'        
    AnacFormNAG2Type:
      description: Contiene tutti i dati relativi alla mancata aggiudicazione della gara - procedura nazionale
      type: object
      allOf: 
      - $ref: '#/components/schemas/AnacFormNAG2DatiBaseType'      
      additionalProperties: false
    SchedaNAG2Type:
      description: Scheda di mancata aggiudicazione della gara - procedura nazionale
      type: object
      required: [anacFormNAG2]
      additionalProperties: false
      properties:
        anacFormNAG2:
          $ref: '#/components/schemas/AnacFormNAG2Type' 