openapi: 3.0.0
info:
  title: Modello Dati - Scheda A4_6 - Scheda di aggiudicazione relativa ai contratti di partenariato sociale.
  version: 1.0.0
components:
  schemas:
    AnacFormA4_6Type:
      description: Contiene i dati per la scheda di aggiudicazione relativa ai contratti di partenariato sociale.
      type: object
      required: [appalto,aggiudicazioni] 
      additionalProperties: false
      properties:
        appalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoA4Type'
        aggiudicazioni:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA4Type'    
    SchedaA4_6Type:
      description: Scheda di aggiudicazione relativa ai contratti di partenariato sociale.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA4_6Type'          