openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD1.28 - Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform28.
  version: 1.0.0
components:
  schemas:
    AggiudicazioneAD1.28Type:
      description: Oggetto che riporta i dati delle aggiudicazioni per gli affidamenti diretti.
      type: object
      required: [afferenteInvestimentiPNRR,lotIdentifier]
      properties:
        cig:
          description: codice identificativo lotto
          type: string
          example: 9050626CD6
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string       
        afferenteInvestimentiPNRR:
          description: L’appalto o concessione è afferente gli investimenti pubblici finanziati, in tutto o in parte, con le risorse previste dal PNRR (Piano Nazionale di Ripresa e Resilienza) e/o dal PNC (Piano nazionale per gli investimenti complementari)?
          type: boolean 
        cupLotto:
          description: Cup associati al lotto
          type: array
          items: 
            type: string  
        paritaDiGenereGenerazionale:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ParitaDiGenereGenerazionaleType'  
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoType'
        quadroEconomicoConcessioni:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoConcessioniType'          
        aggiudicatari:
          description: Aggiudicatari
          type: array
          items: 
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicatarioType' 
        finanziamenti:
          description: Dati relativi ai finanziamenti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/FinanziamentoType'             
    AppaltoAD1.28Type:
      description: Oggetto che riporta i dati inerenti l'affidamento diretto soprasoglia e sottosoglia con pubblicazione su TED - Avviso volontario per la trasparenza ex ante — direttiva sulle concessioni. Articolo 3 bis delle direttive 89/665/CEE e 92/13/CEE
      type: object
      required: [opereUrbanizzazioneScomputo,preinformazione]
      additionalProperties: false
      properties:
        idAppalto:
          description: Codice univoco dell'appalto. il campo viene determinato da anac e restituito nelle response. viene dunque ignorato il valore inserito nelle put/post.
          type: string       
        motivoUrgenza:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoUrgenzaEnum'       
        linkDocumenti:
          description: Link ai documenti relativi all’affidamento diretto in somma urgenza e protezione civile (co 10, art 140 nuovo codice)
          type: string
          format: url        
        opereUrbanizzazioneScomputo:
          description: Opere di urbanizzazione a scomputo
          type: boolean
        preinformazione:
          description: E' stata effettuata la preinformazione?
          type: boolean          
    AnacFormAD1.28Type:
      description: Contiene tutti i dati necessari per l'affidamento diretto soprasoglia e sottosoglia con invio al TED – Avviso volontario per la trasparenza ex ante — direttiva sulle concessioni. Articolo 3 bis delle direttive 89/665/CEE e 92/13/CEE 
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoAD1.28Type'
        aggiudicazioni:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneAD1.28Type'          
    SchedaAD1.28Type:
      description: Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform28.
      type: object
      required: [anacFormAD1.28, eform]
      additionalProperties: false
      properties:
        anacFormAD1.28:
          $ref: '#/components/schemas/AnacFormAD1.28Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType' 
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'        