openapi: 3.0.0
info:
  title: Modello Dati - Scheda SA1 - Scheda di SAL.
  version: 1.0.0
components:
  schemas:
    AvanzamentoType:
      description: Oggetto che riporta tutti i dati di avanzamento del contratto 
      type: object
      required: [codContratto,dataAvanzamento,impSal,denominazioneAvanzamento]
      additionalProperties: false
      properties:
        codContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string
        denominazioneAvanzamento: 
          description: Denominazione dello stato di avanzamento
          type: string
        modalitaPagamento:
          $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModalitaPagamentoEnum'
        impAnticipazione:
          description: Eventuale anticipazione 
          type: number
          format: double          
        dataCertificatoAnticipazione:
          description: Data del certificato di pagamento relativo all'anticipazione 
          type: string
          format: datetime
        dataAvanzamento:
          description: Data Stato di avanzamento
          type: string
          format: datetime
        impSal:
          description: Importo stato avanzamento progressivo (cumulato)
          type: number
          format: double
        dataCertificatoMandatoPagamento:
          description: Data di emissione del certificato/mandato di pagamento. Per lavori, indicare la data del certificato. Per servizi e forniture, indicare la data del mandato
          type: string
          format: datetime
        impCertificatoMandatoPagamento:
          description: Importo del certificato/mandato di pagamento. Per lavori, indicare l’importo del certificato. Per servizi e forniture, indicare l’importo del mandato
          type: number
          format: double
        avanzamento:
          $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/AvanzamentoEnum'          
        numGiorniScostamento:
          description: Indicare lo scostamento registrato in numero di giorni
          type: number
          format: integer
        numGiorniProroga:
          description: Indicare il numero di giorni di proroga concessi (non conseguenti a modifiche contrattuali)
          type: number
          format: integer
    AnacFormSA1Type:
      description: Contiene tutti i dati relativi alla scheda di Avanzamenti
      type: object
      required: [avanzamenti]
      additionalProperties: false
      properties: 
        avanzamenti:
          description: dati di avanzamento
          type: array
          items:         
           $ref: '#/components/schemas/AvanzamentoType'          
    SchedaSA1Type:
      description: Scheda di avanzamento
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSA1Type'          