openapi: 3.0.0
info:
  title: Modello Dati - Scheda M2_39 - Scheda di modifica contrattuale - Avviso di modifica di un appalto — direttiva settoriale - Articolo 89, paragrafo 1, della direttiva 2014/25/UE
  version: 1.0.0
components:
  schemas:
    ModificaContrattualeType:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattualeType'
      type: object
      additionalProperties: false
      properties:    
        datiBaseModificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseModificaContrattualeType'   
    AnacFormM2_39Type:
      description: Contiene tutti i dati di modifica contrattuale
      type: object
      additionalProperties: false
      required: [modificheContrattuali]
      properties:
        modificheContrattuali:
         type: array
         items:          
          $ref: '#/components/schemas/ModificaContrattualeType' 
    SchedaM2_39Type:
      description: Scheda di modifica contrattuale - Avviso di modifica di un appalto — direttiva settoriale - Articolo 89, paragrafo 1, della direttiva 2014/25/UE
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormM2_39Type'