openapi: 3.0.0
info:
  title: Modello Dati - Scheda RI1 - Scheda di ripresa prestazione.
  version: 1.0.0
components:
  schemas:
    SospensioneType:
      description: Oggetto che riporta tutti i dati delle Sospensioni
      type: object
      required: [idContratto, superatoTempo, riserve, verbaleNonSottoscritto]
      additionalProperties: false
      properties:
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6" 
        dataVerbaleRipresa:
          description: Data del verbale di ripresa
          type: string
          format: date-time
        superatoTempo:
          description: E’ stato superato il quarto del tempo contrattuale
          type: boolean   
        riserve:
          description: Iscrizione di riserve dell’appaltatore nei verbali di sospensione e/o ripresa lavori 
          type: boolean   
        verbaleNonSottoscritto:
          description: Verbale/i non sottoscritti dall’appaltatore
          type: boolean
    AnacFormRI1Type:
      description: Contiene tutti i dati relativi alla scheda di ripresa prestazioni
      type: object
      required: [sospensioni]
      additionalProperties: false
      properties:
         sospensioni:
          description: Sospensioni
          type: array
          items:
            $ref: '#/components/schemas/SospensioneType'           
    SchedaRI1Type:
      description: Scheda di ripresa prestazioni
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormRI1Type'