openapi: 3.0.0
info:
  title: Modello Dati - Scheda S2 - Per la procedura a fase unica è l'elenco dei soggetti che hanno presentato offerta. Per le procedure a due fasi è l'elenco dei soggetti invitati e di quelli che non hanno presentato offerta.
  version: 1.0.0
components:
  schemas:
    ElencoSoggettiType:
      description: Elenco di soggetti che hanno presentato offerta e di ulteriori invitati che non hanno presentato offerta.
      type: object
      additionalProperties: false
      required: [cig, dataScadenzaPresentazioneOfferta,partecipanti]
      properties:
        cig:
          description: codice identificativo lotto
          type: string
        invitatiCheNonHannoPresentatoOfferta:
          description: Dati relativi ai soggetti invitati che non hanno presentato offerta
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/InvitatoType'
        partecipanti:
          description: Dati relativi ai partecipanti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/PartecipanteType'              
        dataInvito: 
          description: Data della lettera di invito
          type: string
          format: date-time
        dataScadenzaPresentazioneOfferta: 
          description: Data della scadenza di presentazione dell'offerta
          type: string
          format: date-time        
      
    SchedaS2Type:
      description: Per la procedura a fase unica è l'elenco dei soggetti che hanno presentato offerta. Per le procedure a due fasi è l'elenco dei soggetti invitati e di quelli che non hanno presentato offerta.
      type: object
      additionalProperties: false
      required: [anacForm]
      properties:
        anacForm:
          type: object
          additionalProperties: false
          required: [elencoSoggetti]
          properties:
            elencoSoggetti:
              type: array
              items:
                $ref: '#/components/schemas/ElencoSoggettiType'              
                       