openapi: 3.0.0
info:
  title: Modello Dati - Scheda RI1 - Scheda di riavvio.
  version: 1.0.0
components:
  schemas:
    EsecuzioneType:
      description: Oggetto che riporta i dati di riavvio.
      type: object
      additionalProperties: false
    AnacFormRI1Type:
      description: Contiene tutti i dati di riavvio
      type: object
      additionalProperties: false
      properties:  
        esecuzione:
          $ref: '#/components/schemas/EsecuzioneType'
    SchedaRI1Type:
      description: Scheda di riavvio
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormRI1Type'