openapi: 3.0.0
info:
  title: Modello Dati - Scheda M2_40 - Scheda di modifica contrattuale - Avviso di modifica di un appalto — direttiva sulle concessioni - Articolo 43, paragrafo 1, della direttiva 2014/23/UE
  version: 1.0.0
components:
  schemas:
    ModificaContrattualeType:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattuale.40Type'
      type: object
      additionalProperties: false
      properties:    
        datiBaseModificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseModificaContrattualeType'   
    AnacFormM2_40Type:
      description: Contiene tutti i dati di modifica contrattuale
      type: object
      additionalProperties: false
      properties:  
        modificaContrattuale:
          $ref: '#/components/schemas/ModificaContrattualeType'       
    SchedaM2_40Type:
      description: Scheda di modifica contrattuale - Avviso di modifica di un appalto — direttiva sulle concessioni - Articolo 43, paragrafo 1, della direttiva 2014/23/UE
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormM2_40Type'