openapi: 3.0.0
info:
  title: Modello Dati - Scheda M1.40 - Scheda di modifica contrattuale con invio al TED - Avviso di modifica di un appalto — direttiva sulle concessioni - Articolo 43, paragrafo 1, della direttiva 2014/23/UE
  version: 1.0.0
components:
  schemas:
    AnacFormM1.40Type:
      description: Contiene tutti i dati relativi alle modifiche contrattuali con invio al TED - Avviso di modifica di un appalto — direttiva sulle concessioni - Articolo 43, paragrafo 1, della direttiva 2014/23/UE
      type: object
      additionalProperties: false
      properties:
        modificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattualeType' 
        quadroEconomicoConcessioni:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoConcessioniType'
    SchedaM1.40Type:
      description: Scheda di modifica contrattuale con invio al TED - Avviso di modifica di un appalto — direttiva sulle concessioni - Articolo 43, paragrafo 1, della direttiva 2014/23/UE
      type: object
      required: [anacFormM1]
      additionalProperties: false
      properties:
        anacFormM1:
          $ref: '#/components/schemas/AnacFormM1.40Type'
        eform:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'           