openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD1.27 - Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform27.
  version: 1.0.0
components:
  schemas:
    AggiudicatarioType:
      description: Dati dell'aggiudicatario
      type: object
      required: [denominazione,ruolo,tipo,importo]
      additionalProperties: false
      properties:
        cf:
          description: codice fiscale del soggetto aggiudicatario
          type: string
        identificativoCfEstero:
          description: Identificativo codice fiscale estero (eventuale)
          type: string
        denominazione: 
          description: denominazione dell'aggiudicatario
          type: string  
        ruolo: 
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/RuoloOEEnum'
        idGruppo:
          description: id gruppo
          type: string 
        importo:
          description: Importo di aggiudicazione
          type: string
          format: decimal  
        dataInizio:
          description: Data inizio (per L/S/F)
          type: string
          format: datetime
        dataUltimazione:
          description: Data ultimazione
          type: string
          format: datetime
        sommeLiquidate:
          description: Importo delle somme liquidate
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ImportoType' 
    LottoAD1.27Type:
      description: Oggetto che riporta i dati del lotto per gli affidamento diretti.
      type: object
      required: [lotIdentifier,oggettoLotto,sceltaContraente]
      properties:  
        cig:
          description: codice identificativo lotto
          type: string
          example: 9050626CD6
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string      
        oggettoLotto:
          description: oggetto del lotto
          type: string          
        sceltaContraente:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/SceltaContraenteEnum'   
    AggiudicazioneAD1.27Type:
      description: Oggetto che riporta i dati inerenti la fase di aggiudicazione per l'affidamento diretto soprasoglia e sottosoglia con pubblicazione su TED - Avviso volontario per la trasparenza ex ante — direttiva per il settore della difesa - Articolo 64 della direttiva 2009/81/CE
      type: object
      additionalProperties: false 
      properties:
        motivoUrgenza:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoUrgenzaEnum'       
        linkDocumenti:
          description: Link ai documenti relativi all’affidamento diretto in somma urgenza e protezione civile (co 10, art 140 nuovo codice)
          type: string
          format: url
        cfSA: 
          description: Codice fiscale SA
          type: string
        denominazioneSA: 
          description: Denominazione SA
          type: string   
    AnacFormAD1.27Type:
      description: Contiene tutti i dati necessari per l'affidamento diretto soprasoglia e sottosoglia con invio al TED – Avviso volontario per la trasparenza ex ante — direttiva per il settore della difesa. Articolo 64 della direttiva 2009/81/CE 
      type: object
      required: [aggiudicazione,lotti]
      additionalProperties: false
      properties:  
        aggiudicazione:
          $ref: '#/components/schemas/AggiudicazioneAD1.27Type' 
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoAD1.27Type' 
        aggiudicatario:
          $ref: '#/components/schemas/AggiudicatarioType'
    SchedaAD1.27Type:
      description: Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform27.
      type: object
      required: [anacFormAD1.27, eform]
      additionalProperties: false
      properties:
        anacFormAD1.27:
          $ref: '#/components/schemas/AnacFormAD1.27Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType' 
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         