openapi: 3.0.0
info:
  title: Modello Dati - Scheda STAQ - Scheda di Stipula AQ/Convenzione
  version: 1.0.0
components:
  schemas:
    DatiStipulaType:
      description: Oggetto che riporta i dati di Stipula AQ/Convenzione
      type: object
      additionalProperties: false
      properties:
        codContratto:
          description: identificativo del contratto restituito in response alla scheda di Inizio Lavori.
          type: string      
        dataStipula:
          description: Data stipula accordo quadro/convenzione
          type: string
          format: datetime
        dataDecorrenza:
          description: Data decorrenza contrattuale
          type: string
          format: datetime
        dataScadenza:
          description: Data scadenza contrattuale
          type: string
          format: datetime
    AnacFormSTAQType:
      description: Contiene tutti i dati di Stipula AQ/Convenzione
      type: object
      additionalProperties: false
      properties:  
        datiStipula:
          $ref: '#/components/schemas/DatiStipulaType'
    SchedaSTAQType:
      description: Scheda di Stipula AQ/Convenzione
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSTAQType'