openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD1.25 - Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform25.
  version: 1.0.0
components:
  schemas:
    AnacFormAD1.25Type:
      description: Contiene tutti i dati necessari per l'affidamento diretto soprasoglia e sottosoglia con invio al TED – Avviso volontario per la trasparenza ex ante — direttiva generale. Articolo 3 bis della direttiva 89/665/CEE
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false
      properties:  
        appalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoAD1.25Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneAD1.25Type'
    SchedaAD1.25Type:
      description: Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform25.
      type: object
      required: [anacForm, eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormAD1.25Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'         
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         