openapi: 3.0.0
info:
  title: Modello Dati - Scheda M2.40 - Scheda di modifica contrattuale - Avviso di modifica di un appalto — direttiva sulle concessioni - Articolo 43, paragrafo 1, della direttiva 2014/23/UE
  version: 1.0.0
components:
  schemas:
    AnacFormM2.40Type:
      description: Contiene tutti i dati di modifica contrattuale
      type: object
      additionalProperties: false
      properties:  
        modificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattualeType' 
        quadroEconomicoConcessioni:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoConcessioniType'
        datiBaseModificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseModificaContrattualeType'       
    SchedaM2.40Type:
      description: Scheda di modifica contrattuale - Avviso di modifica di un appalto — direttiva sulle concessioni - Articolo 43, paragrafo 1, della direttiva 2014/23/UE
      type: object
      required: [anacFormM2]
      additionalProperties: false
      properties:
        anacFormM2:
          $ref: '#/components/schemas/AnacFormM2.40Type'