openapi: 3.0.0
info:
  title: Modello Dati - Scheda CO1 - Scheda di conclusione.
  version: 1.0.0
components:
  schemas:
    ConclusioneType:
      description: Oggetto che riporta i dati di conclusione.
      type: object
      additionalProperties: false
    AnacFormCO1Type:
      description: Contiene tutti i dati di conclusione
      type: object
      additionalProperties: false
      properties:  
        conclusione:
          $ref: '#/components/schemas/ConclusioneType'
    SchedaCO1Type:
      description: Scheda di conclusione
      type: object
      required: [anacFormCO1]
      additionalProperties: false
      properties:
        anacFormCO1:
          $ref: '#/components/schemas/AnacFormCO1Type'