openapi: 3.0.0
info:
  title: Modello Dati - Scheda PL2_3 - Scheda di pianificazione per appalti settore difesa e sicurezza sotto soglia, senza invio al TED.
  version: 1.0.0
components:
  schemas: 
    SchedaPL2_3Type:
      description: Scheda di pianificazione per appalti settore difesa e sicurezza sotto soglia, senza invio al TED.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormPLBaseType'    