openapi: 3.0.0
info:
  title: Modello Dati - Scheda A1.31 - Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED - Avviso di aggiudicazione di una concessione — direttiva per il settore della difesa. Articolo 30, paragrafo 3, della direttiva 2009/81/CE con invio di eform31.
  version: 1.0.0
components:
  schemas:
    AnacFormA1.31Type:
      description: Contiene tutti i dati relativi all'aggiudicazione soprasoglia e sottosoglia con invio al TED - Avviso di aggiudicazione di una concessione — direttiva per il settore della difesa. Articolo 30, paragrafo 3, della direttiva 2009/81/CE
      type: object
      required: [aggiudicazioni]
      additionalProperties: false
      properties:
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:       
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA1.31Type'      
    SchedaA1.31Type:
      description: Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED - Avviso di aggiudicazione di una concessione — direttiva per il settore della difesa. Articolo 30, paragrafo 3, della direttiva 2009/81/CE con invio di eform31.
      type: object
      required: [anacFormA1, eform]
      additionalProperties: false
      properties:
        anacFormA1:
          $ref: '#/components/schemas/AnacFormA1.31Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'         