openapi: 3.0.0
info:
  title: Modello Dati - Scheda NAG2 - Scheda di Mancata aggiudicazione procedura nazionale
  version: 1.0.0
components:
  schemas:
    AggiudicazioneNAG2Type:
      description: Oggetto che riporta i dati dell'aggiudicazione
      type: object
      additionalProperties: false
    AnacFormNAG2Type:
      description: Contiene tutti i dati di Mancata aggiudicazione procedura nazionale
      type: object
      additionalProperties: false
      properties:  
        aggiudicazione:
          $ref: '#/components/schemas/AggiudicazioneNAG2Type'
    SchedaNAG2Type:
      description: Scheda di Mancata aggiudicazione procedura nazionale
      type: object
      required: [anacFormNAG]
      additionalProperties: false
      properties:
        anacFormNAG:
          $ref: '#/components/schemas/AnacFormNAG2Type'