openapi: 3.0.0
info:
  title: Modello Dati - Scheda C2 - Scheda di annullamento procedura o comunicazione nuovo importo per appalti sopra i 5K euro.
  version: 1.0.0
components:
  schemas:
    AnacFormC2Type:
      type: object
      required: [cig,comunicazione]
      additionalProperties: false
      properties:
        cig:
          description: codice identificativo lotto
          type: string 
        comunicazione:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ComunicazioneType'              
    SchedaC2Type:
      description: Scheda di annullamento procedura o comunicazione nuovo importo per appalti sopra i 5K euro.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormC2Type'