openapi: 3.0.0
info:
  title: Modello Dati - Scheda SO1 - Scheda di sospensione.
  version: 1.0.0
components:
  schemas:
    EsecuzioneType:
      description: Oggetto che riporta i dati di sospensione.
      type: object
      additionalProperties: false
    AnacFormSO1Type:
      description: Contiene tutti i dati di sospensione
      type: object
      additionalProperties: false
      properties:  
        esecuzione:
          $ref: '#/components/schemas/EsecuzioneType'
    SchedaSO1Type:
      description: Scheda di sospensione
      type: object
      required: [anacFormSO1]
      additionalProperties: false
      properties:
        anacFormSO1:
          $ref: '#/components/schemas/AnacFormSO1Type'