openapi: 3.0.0
info:
  title: Modello Dati - Scheda P3.1 - Scheda di pubblicazione relativa ai contratti esclusi (generale o di tipo accordo quadro).
  version: 1.0.0
components:
  schemas:
    LottoP3.1Type:
      description: Oggetto che riporta i dati del lotto all'interno della fase di pubblicazione sopra soglia e sotto soglia
      allOf: # estende la classe LottoP3BaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP3BaseType'      
      type: object
      required: [afferenteInvestimentiPNRR,motivoEsclusioneOrdinarioSpeciale]
      additionalProperties: false
      properties:
        motivoEsclusioneOrdinarioSpeciale: 
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoEsclusioneOrdinarioSpecialeEnum'  
        opzioni/rinnovi:
          description: L’appalto prevede opzioni/rinnovi?
          type: boolean
    AppaltoP3.1Type:
      description: Oggetto che riporta i dati dell'appalto relativi ai contratti esclusi (generale o di tipo accordo quadro)
      allOf: # estende la classe AppaltoP3BaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP3BaseType'      
      type: object
      additionalProperties: false
    AnacFormP3.1Type:
      description: Contiene i dati relativi ai contratti esclusi (generale o di tipo accordo quadro)
      allOf: # estende la classe AnacFormP3ContrattiEsclusiDatiBaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormP3ContrattiEsclusiDatiBaseType'       
      type: object
      required: [categoria, finanziamenti, appalto,lotti]
      additionalProperties: false
      properties:  
        appalto: 
          $ref: '#/components/schemas/AppaltoP3.1Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP3.1Type'          
        stazioniAppaltanti:
          description: Dati relativi alle stazioni appaltanti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/StazioneAppaltanteType'    
        finanziamenti:
          description: Dati relativi ai finanziamenti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/FinanziamentoType'
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoP3ContrattiEsclusiType'              
    SchedaP3.1Type:
      description: Scheda di pubblicazione relativa ai contratti esclusi (generale o di tipo accordo quadro)
      type: object
      required: [anacFormP3, anacFormP3DatiBase]
      additionalProperties: false
      properties:
        anacFormP3:
          $ref: '#/components/schemas/AnacFormP3.1Type' 
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         