openapi: 3.0.0
info:
  title: Modello Dati - Scheda CO01 - Scheda di conclusione.
  version: 1.0.0
components:
  schemas:
    ConclusioneType:
      description: Oggetto che riporta i dati di conclusione.
      type: object
      additionalProperties: false
    AnacFormCO01Type:
      description: Contiene tutti i dati di conclusione
      type: object
      additionalProperties: false
      properties:  
        conclusione:
          $ref: '#/components/schemas/ConclusioneType'
    SchedaCO01Type:
      description: Scheda di conclusione
      type: object
      required: [anacFormCO01]
      additionalProperties: false
      properties:
        anacFormCO01:
          $ref: '#/components/schemas/AnacFormCO01Type'