openapi: 3.0.0
info:
  title: Modello Dati - Scheda M2.38 - Scheda di modifica contrattuale - Avviso di modifica di un appalto — direttiva generaleArticolo 72, paragrafo 1, della direttiva 2014/24/UE
  version: 1.0.0
components:
  schemas:
    AnacFormM2.38Type:
      description: Contiene tutti i dati di modifica contrattuale
      type: object
      additionalProperties: false
      properties:  
        modificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattualeType' 
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoModificaContrattualeType'
        datiBaseModificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseModificaContrattualeType'          
    SchedaM2.38Type:
      description: Scheda relativa alle modifiche contrattuali senza invio al TED - Avviso di modifica di un appalto — direttiva generaleArticolo 72, paragrafo 1, della direttiva 2014/24/UE
      type: object
      required: [anacFormM2]
      additionalProperties: false
      properties:
        anacFormM2:
          $ref: '#/components/schemas/AnacFormM2.38Type'
         