openapi: 3.0.0
info:
  title: Modello Dati - Scheda CM1 - Scheda di comunicazione modifica dati della procedura per appalti sopra i 5K euro.
  version: 1.0.0
components:
  schemas:
    AnacFormCM1Type:
      type: object
      required: [cig,motivo]
      additionalProperties: false
      properties:
        cig:
          description: codice identificativo lotto
          type: string 
        motivo:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/changelog_priorita_0/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoRichiestaModificaEnum'
        importo:
          description: Importo
          type: number
          format: double
        cup:
          description: Cup
          type: string        
    SchedaCM1Type:
      description: Scheda di comunicazione modifica dati della procedura per appalti sopra i 5K euro.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormCM1Type'