openapi: 3.0.0
info:
  title: Modello Dati - Scheda P2.21- Scheda di pubblicazione avviso per un bando di gara sottosoglia maggiore di 5K - Avviso di gara — direttiva settoriale, regime alleggerito. Articolo 92, paragrafo 1, lettera a),della direttiva 2014/25/UE.
  version: 1.0.0
components:
  schemas:
    AppaltoP2.21Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP.21Type'
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoBaseType'      
      type: object
      additionalProperties: false
      properties:  
        datiBase:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAppaltoP2.21Type'
        datiBaseProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraType'

        datiBaseStrumentiProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseStrumentiProceduraType'      
    LottoP2.21Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP.21Type'
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoBaseType'      
      type: object
      additionalProperties: false
      properties:  
        datiBase:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseLottoP2.21Type'      
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiTerminiInvioType'  
        datiBaseCPV:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseCPVType'
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType'  
        datiBaseContratto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseContrattoType' 
        datiBaseAggiuntivi:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiuntiviType'        
        datiBaseAggiudicazione:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneType'            
    AnacFormP2.21Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale di un bando di gara sottosoglia maggiore di 5K - Avviso di gara — direttiva settoriale, regime alleggerito. Articolo 92, paragrafo 1, lettera a),della direttiva 2014/25/UE
      allOf:  
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'      
      type: object
      additionalProperties: false
      required: [finanziamenti,opzioni/rinnovi, appalto,lotti]
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoP2.21Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP2.21Type'
    SchedaP2.21Type:
      description: Scheda di pubblicazione avviso per un bando di gara sottosoglia maggiore di 5K - Avviso di gara — direttiva settoriale, regime alleggerito. Articolo 92, paragrafo 1, lettera a),della direttiva 2014/25/UE
      type: object
      required: [anacFormP2,espd]
      additionalProperties: false
      properties:
        anacFormP2:
          $ref: '#/components/schemas/AnacFormP2.21Type'
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         
