openapi: 3.0.0
info:
  title: Modello Dati - Scheda P3.3 - Scheda di pubblicazione relativa ai contratti esclusi - adesione con confronto competitivo.
  version: 1.0.0
components:
  schemas:
    LottoP3.3Type:
      description: Oggetto che riporta i dati del lotto all'interno della fase di pubblicazione sopra soglia e sotto soglia
      allOf: # estende la classe LottoP3BaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP3BaseType'      
      type: object
      required: [afferenteInvestimentiPNRR,opzioni/rinnovi, categoria,motivoEsclusioneOrdinarioSpeciale]
      additionalProperties: false
      properties:
        motivoEsclusioneOrdinarioSpeciale: 
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoEsclusioneOrdinarioSpecialeEnum'
    AppaltoP3.3Type:
      description: Oggetto che riporta i dati dell'appalto relativi ai contratti esclusi - adesione con confronto competitivo
      allOf: # estende la classe AppaltoP3BaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP3BaseType'  
      type: object
      required: [motivoEsclusioneOrdinarioSpeciale,cigAccordoQuadro]
      additionalProperties: false
      properties:      
        cigAccordoQuadro:
          description: CIG relativo all’accordo quadro/convenzione cui si aderisce
          type: string
          example: ''      
    AnacFormP3.3Type:
      description: Contiene i dati relativi ai contratti esclusi - adesione con confronto competitivo
      allOf: # estende la classe AnacFormP3ContrattiEsclusiDatiBaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormP3ContrattiEsclusiDatiBaseType'       
      type: object
      required: [categoria, finanziamenti, appalto]
      additionalProperties: false
      properties:  
        appalto: 
          $ref: '#/components/schemas/AppaltoP3.3Type'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP3.3Type'          
        stazioniAppaltanti:
          description: Dati relativi alle stazioni appaltanti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/StazioneAppaltanteType'    
        finanziamenti:
          description: Dati relativi ai finanziamenti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/FinanziamentoType'     
        quadroEconomicoStandard:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoP3ContrattiEsclusiType' 
    SchedaP3.3Type:
      description: Scheda di pubblicazione relativa ai contratti esclusi - adesione con confronto competitivo
      type: object
      required: [anacFormP3, anacFormP3DatiBase]
      additionalProperties: false
      properties:
        anacFormP3:
          $ref: '#/components/schemas/AnacFormP3.3Type'  
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'          