openapi: 3.0.0
info:
  title: Modello Dati - Scheda P4_6 - Scheda di Contratti di parternariato sociale.
  version: 1.0.0
components:
  schemas:
   AnacFormP4_6Type:
      description: Contiene i dati per la scheda di Contratti di parternariato sociale
      allOf: # estende la classe AnacFormBaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'       
      type: object
      required: [appalto,lotti] 
      additionalProperties: false
      properties:
        appalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP4BaseType'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP4BaseType'    
   SchedaP4_6Type:
      description: Scheda di Contratti di parternariato sociale.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP4_6Type' 
        eform:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'          
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'          