openapi: 3.0.0
info:
  title: Modello Dati - Scheda PL1_08 - Scheda di pianificazione per appalti settori speciali pari /sopra soglia con invio al TED dell'eform8.
  version: 1.0.0
components:
  schemas:          
    SchedaPL1_08Type:
      description: Scheda di pianificazione per appalti settori speciali pari /sopra soglia con invio al TED dell'eform8.
      type: object
      required: [eform]
      additionalProperties: false
      properties:
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'            
         