openapi: 3.0.0
info:
  title: Modello Dati - Scheda NAG1 - Scheda di mancata aggiudicazione della gara - sopra soglia europea
  version: 1.0.0
components:
  schemas:
    AnacFormNAG1Type:
      description: Contiene tutti i dati relativi alla mancata aggiudicazione della gara - sopra soglia europea
      type: object
      additionalProperties: false
      properties:
        esitoProceduraNag:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EsitoProceduraNagEnum'
    SchedaNAG1Type:
      description: Scheda di mancata aggiudicazione della gara - sopra soglia europea
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormNAG1Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'          