openapi: 3.0.0
info:
  title: Modello Dati - Scheda SO1 - Scheda di sospensione.
  version: 1.0.0
components:
  schemas:
    SospensioneType:
      description: Oggetto che riporta tutti i dati delle Sospensioni
      type: object
      required: [codContratto, dataVerbaleSospensione, motivoSospensione]
      additionalProperties: false
      properties:
        codContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string 
        sospensioneParziale: 
          description: La sospensione è parziale?
          type: boolean
        dataVerbaleSospensione: 
          description: Data del verbale di sospensione
          type: string
          format: datetime
        motivoSospensione:
          $ref: 'https://raw.githubusercontent.com/ctribo/yaml/main/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoSospensioneEnum'
    AnacFormSO1Type:
      description: Contiene tutti i dati relativi alla scheda di Sospensione
      type: object
      required: [sospensioni]
      additionalProperties: false
      properties:
         sospensioni:
          description: Sospensioni
          type: array
          items:
            $ref: '#/components/schemas/SospensioneType'           
    SchedaSO1Type:
      description: Scheda di sospensione
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormSO1Type'