openapi: 3.0.0
info:
  title: Modello Dati - Scheda P7_2 - Scheda relativa a RDO da elenco fornitori
  version: 1.0.0
components:
  schemas:
   LottoP7_2Type:
      description: Oggetto che riporta i dati del lotto all'interno della scheda di RDO da elenco fornitori
      allOf: # estende la classe LottoP7BaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP7BaseType'      
      type: object
      additionalProperties: false
      required: [ripetizioniEConsegneComplementari,opzioniRinnovi]
      properties:
        ripetizioniEConsegneComplementari:
          description: L’appalto prevede ripetizioni di servizi/forniture/lavori analoghi e consegne complementari?
          type: boolean   
        opzioniRinnovi:
          description: L’appalto prevede opzioni/rinnovi?
          type: boolean  
        quadroEconomicoStandard:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoType'  
          required: [sommeOpzioniRinnovi,sommeRipetizioni]          
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseTerminiInvioSoloOraType'
   AnacFormP7_2Type:
      description: Contiene i dati per la scheda di RDO da elenco fornitori
      allOf: # estende la classe AnacFormBaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'   
      type: object
      required: [appalto,lotti] 
      additionalProperties: false
      properties:
        appalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP7BaseType'
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/LottoP7_2Type'    
   SchedaP7_2Type:
      description: Scheda relativa a RDO da elenco fornitori.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP7_2Type'   
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'           