openapi: 3.0.0
info:
  title: Modello Dati - Scheda CS1 - Scheda di conclusione subappalto.
  version: 1.0.0
components:
  schemas:
    SubappaltoType:
      description: Dati relativi ai subappalti
      type: object
      required: [idContratto,importoEffettivo]
      additionalProperties: false
      properties:    
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6" 
        importoEffettivo: 
          description: Importo effettivo Lavoro/ Servizio/Fornitura, subappalto
          type: number
          format: double
        dataUltimazione: 
          description: Termine di ultimazione della prestazione di subappalto
          type: string
          format: date-time
    AnacFormCS1Type:
      description: Contiene tutti i dati relativi alla scheda di conclusione di subappalto
      type: object
      required: [subappalti]
      additionalProperties: false
      properties: 
        subappalti:
          type: array
          items:
            $ref: '#/components/schemas/SubappaltoType'
    SchedaCS1Type:
      description: Scheda di conclusione subappalto
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormCS1Type'