openapi: 3.0.0
info:
  title: Modello Dati - Scheda A2.31 - Scheda relativa all'aggiudicazione sottosoglia senza invio al TED - Avviso di aggiudicazione di una concessione — direttiva per il settore della difesa. Articolo 30, paragrafo 3, della direttiva 2009/81/CE.
  version: 1.0.0
components:
  schemas:
    AggiudicatarioA2.31Type:
      description: Dati dell'aggiudicatario
      allOf: # estende la classe AggiudicatarioType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicatarioType'      
      type: object
      additionalProperties: false
      properties:
        identificativoCfEstero:
            description: Identificativo codice fiscale estero
            type: string            
        dataInizio:
            description: Data inizio
            type: string
            format: datetime
        dataUltimazione:
            description: Data ultimazione
            type: string
            format: datetime
        impSommeLiquidate:
            description: importo delle somme liquidate
            type: string
            format: decimal   
    AnacFormA2.31DatiBaseType:
      description: Oggetto che contiene gli oggetti comuni con il TED relativi alle aggiudicazioni sottosoglia - Avviso di aggiudicazione di una concessione — direttiva per il settore della difesa. Articolo 30, paragrafo 3, della direttiva 2009/81/CE
      allOf: # estende la classe AnacFormA2DatiBaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormA2DatiBaseType'       
      type: object
      additionalProperties: false
      properties:
        datiBaseProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraA2.31Type'
        datiBaseStrumentiProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseStrumentiProceduraA2.31Type'
        datiBaseSottomissioniRicevute:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSottomissioniRicevuteType'
        datiBaseAggiudicazioneSubappalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneSubappaltoType' 
    AnacFormA2.31Type:
      description: Contiene tutti i dati relativi all'aggiudicazione sottosoglia senza invio al TED - Avviso di aggiudicazione di una concessione — direttiva per il settore della difesa. Articolo 30, paragrafo 3, della direttiva 2009/81/CE
      allOf: 
      - $ref: '#/components/schemas/AnacFormA2.31DatiBaseType'
      type: object
      required: [aggiudicatari]
      additionalProperties: false
      properties:
        aggiudicatari:
          description: Dati degli aggiudicatari
          type: array
          items: 
            $ref: '#/components/schemas/AggiudicatarioA2.31Type'     
    SchedaA2.31Type:
      description: Scheda relativa all'aggiudicazione sottosoglia senza invio al TED - Avviso di aggiudicazione di una concessione — direttiva per il settore della difesa. Articolo 30, paragrafo 3, della direttiva 2009/81/CE.
      type: object
      required: [anacFormA2]
      additionalProperties: false
      properties:
        anacFormA2:
          $ref: '#/components/schemas/AnacFormA2.31Type'          