openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD1.27 - Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform27.
  version: 1.0.0
components:
  schemas:
    AggiudicazioneAD1.27Type:
      description: Oggetto che riporta i dati delle aggiudicazioni per gli affidamenti diretti.
      type: object
      required: [lotIdentifier,oggettoLotto,sceltaContraente]
      properties:  
        cig:
          description: codice identificativo lotto
          type: string
          example: 9050626CD6
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string      
        finanziamenti:
          description: Dati relativi ai finanziamenti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/FinanziamentoType'           
    AppaltoAD1.27Type:
      description: Oggetto che riporta i dati inerenti l'affidamento diretto soprasoglia e sottosoglia con pubblicazione su TED - Avviso volontario per la trasparenza ex ante — direttiva per il settore della difesa - Articolo 64 della direttiva 2009/81/CE
      type: object
      additionalProperties: false 
      properties:
        motivoUrgenza:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoUrgenzaEnum'       
        linkDocumenti:
          description: Link ai documenti relativi all’affidamento diretto in somma urgenza e protezione civile (co 10, art 140 nuovo codice)
          type: string
          format: url
    AnacFormAD1.27Type:
      description: Contiene tutti i dati necessari per l'affidamento diretto soprasoglia e sottosoglia con invio al TED – Avviso volontario per la trasparenza ex ante — direttiva per il settore della difesa. Articolo 64 della direttiva 2009/81/CE 
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoAD1.27Type' 
        aggiudicazioni:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneAD1.27Type' 
    SchedaAD1.27Type:
      description: Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform27.
      type: object
      required: [anacFormAD1.27, eform]
      additionalProperties: false
      properties:
        anacFormAD1.27:
          $ref: '#/components/schemas/AnacFormAD1.27Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType' 
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         