openapi: 3.0.0
info:
  title: Modello Dati - Scheda S0 - Elenco richieste di adesione SDA
  version: 1.0.0
components:
  schemas:
    PartecipanteSDAType:
      allOf: 
          - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/PartecipanteType'
      type: object
      required: [statoSDA, ammesso] 
      additionalProperties: false
      properties:
        statoSDA:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/StatoSDAEnum' 
        ammesso:
          description: Ammesso?
          type: boolean
    SchedaS0Type:
      description: Elenco richieste di adesione SDA. Articolo 32 comma 7 decreto legislativo 36/2023.
      type: object
      additionalProperties: false
      required: [anacForm]
      properties:
        anacForm:
          type: object
          additionalProperties: false
          required: [idPianificazione,partecipanti,operazioneSDA]
          properties:
            idPianificazione:
              description: id restituito dal servizio all'invio della scheda di istituzione SDA
              type: string 
            operazioneSDA: 
              $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/OperazioneSDAEnum' 
            partecipanti:
              description: Dati relativi ai partecipanti allo SDA
              type: array
              items:
                $ref: '#/components/schemas/PartecipanteSDAType'
                       