openapi: 3.0.0
info:
  title: Modello Dati - Scheda A4_1 - Scheda di aggiudicazione relativa alla finanza di progetto.
  version: 1.0.0
components:
  schemas:
    AnacFormA4_1Type:
      description: Contiene i dati per la scheda di aggiudicazione relativa alla finanza di progetto.
      type: object
      required: [appalto,aggiudicazioni] 
      additionalProperties: false
      properties:
        appalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoA4Type'
    SchedaA4_1Type:
      description: Scheda di aggiudicazione relativa alla finanza di progetto.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA4_1Type'
