openapi: 3.0.0
info:
  title: Modello Dati - Scheda ISDA1 - Istituzione Sistema Dinamico di Acquisizione Sopra soglia.
  version: 1.0.0
components:
  schemas:           
    SchedaISDA1Type:
      description: Istituzione Sistema Dinamico di Acquisizione Sopra soglia. Articolo 32 comma 2, 6 decreto legislativo 36/2023.
      type: object
      required: [anacForm,eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'        
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'         