openapi: 3.0.0
info:
  title: Modello Dati - Scheda P1.15 - Scheda di pubblicazione avviso sull'esistenza di un sistema di qualificazione, con invio al TED dell'eform15.
  version: 1.0.0
components:
  schemas:
    SchedaP1.15Type:
      description: Scheda di pubblicazione avviso sull'esistenza di un sistema di qualificazione, con invio al TED dell'eform15. 
      type: object
      required: [anacFormP1, eform]
      additionalProperties: false
      properties:
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'        