openapi: 3.0.0
info:
  title: Modello Dati - Scheda CL1 - Scheda di collaudo.
  version: 1.0.0
components:
  schemas:
    CollaudoType:
      description: Oggetto che riporta i dati di collaudo.
      type: object
      additionalProperties: false
    AnacFormCL1Type:
      description: Contiene tutti i dati di collaudo
      type: object
      additionalProperties: false
      properties:  
        collaudo:
          $ref: '#/components/schemas/CollaudoType'
    SchedaCL1Type:
      description: Scheda di collaudo
      type: object
      required: [anacFormCL1]
      additionalProperties: false
      properties:
        anacFormCL1:
          $ref: '#/components/schemas/AnacFormCL1Type'