openapi: 3.0.0
info:
  title: Modello Dati - Scheda M1.39 - Scheda di modifica contrattuale con invio eform39.
  version: 1.0.0
components:
  schemas:
    ModificaContrattualeType:
      description: Oggetto che riporta i dati della modifica contrattuale
      type: object
      additionalProperties: false
    AnacFormM1.39Type:
      description: Contiene tutti i dati di modifica contrattuale
      type: object
      additionalProperties: false
      properties:  
        esecuzione:
          $ref: '#/components/schemas/ModificaContrattualeType'
    SchedaM1.39Type:
      description: Scheda di modifica contrattuale
      type: object
      required: [anacFormM1]
      additionalProperties: false
      properties:
        anacFormM1:
          $ref: '#/components/schemas/AnacFormM1.39Type'