openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD1.27 - Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform27.
  version: 1.0.0
components:
  schemas:
    AnacFormAD1.27Type:
      description: Contiene tutti i dati necessari per l'affidamento diretto soprasoglia e sottosoglia con invio al TED – Avviso volontario per la trasparenza ex ante — direttiva per il settore della difesa. Articolo 64 della direttiva 2009/81/CE 
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false
      properties:  
        appalto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoAD1.27Type' 
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneAD1.27Type' 
    SchedaAD1.27Type:
      description: Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform27.
      type: object
      required: [anacFormAD1.27, eform]
      additionalProperties: false
      properties:
        anacFormAD1.27:
          $ref: '#/components/schemas/AnacFormAD1.27Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType' 
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         