openapi: 3.0.0
info:
  title: Modello Dati - Scheda AD5 - Scheda relativa gli appalti di importo inferiore a 5K, senza invio al TED.
  version: 1.0.0
components:
  schemas:
    AggiudicazioneAD5Type:
      type: object
      additionalProperties: false
      properties: 
        cig:
          description: codice identificativo lotto
          type: string
          example: 
        lotIdentifier:
          description: Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
          type: string     
        oggettoContratto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/OggettoContrattoEnum'
        oggettoPrincipaleContratto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/OggettoPrincipaleContrattoEnum'          
        cup:
          description: Cup
          type: string  
        sceltaContraente:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/SceltaContraenteEnum' 
        aggiudicatari:
          type: array
          items:          
            $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicatarioType'     
    AppaltoAD5Type:
      type: object
      additionalProperties: false
      required: [cig,dataAdesione,relazioneUnicaSulleProcedure,opereUrbanizzazioneScomputo]
      properties:   
        idAppalto:
          description: Codice univoco dell'appalto. il campo viene determinato da anac e restituito nelle response. viene dunque ignorato il valore inserito nelle put/post.
          type: string  
        cfSA: 
          description: Codice fiscale SA
          type: string
        denominazioneSA: 
          description: Denominazione SA
          type: string
        categorieMerceologiche:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategorieMerceologicheType'
        motivazioneCIG:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivazioneCIGEnum'
    AnacFormAD5Type:
      description: Contiene tutti i dati relativi agli appalti di importo inferiore a 5K, senza invio al TED. 
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false   
      properties:  
        appalto:
          $ref: '#/components/schemas/AppaltoAD5Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneAD5Type'      
    SchedaAD5Type:
      description: Scheda relativa gli appalti di importo inferiore a 5K, senza invio al TED.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormAD5Type'