openapi: 3.0.0
info:
  title: Modello Dati - Scheda P2.17 - Scheda di pubblicazione avviso per un bando di gara sottosoglia maggiore di 5K - Bando di gara — direttiva settoriale, regime ordinario. Articolo 69 della direttiva 2014/25/UE.
  version: 1.0.0
components:
  schemas:
    AnacFormP2.17DatiBaseType:
      description: Oggetto che contiene gli oggetti comuni con il TED per le pubblicazioni sottosoglia > 5K - Bando di gara — direttiva settoriale, regime ordinario. Articolo 69 della direttiva 2014/25/UE
      allOf: # estende la classe AnacFormP2DatiBaseType
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormP2DatiBaseType' 
      type: object
      #required: []
      additionalProperties: false
      properties:
        datiBase:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseType'
        datiBaseProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraP2.17Type'
        datiBaseContratto:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseContrattoType' 
        datiBaseAggiuntivi:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiuntiviType'        
        datiBaseAggiudicazione:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneType'
        datiBaseStrumentiProcedura:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseStrumentiProceduraP2.17Type'
        datiBaseTerminiInvio:
          $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiTerminiInvioType' 
    AnacFormP2.17Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale di un bando di gara sottosoglia maggiore di 5K — direttiva settoriale, regime ordinario. Articolo 69 della direttiva 2014/25/UE 
      allOf: # estende la classe AnacFormP1.17Type
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.17.yaml#/components/schemas/AnacFormP1.17Type' 
      - $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'      
      - $ref: '#/components/schemas/AnacFormP2.17DatiBaseType'
      type: object
      additionalProperties: false
      required: [finanziamenti,opzioni/rinnovi, appalto]
    SchedaP2.17Type:
      description: Scheda di pubblicazione avviso per un bando di gara sottosoglia maggiore di 5K - Bando di gara — direttiva settoriale, regime ordinario. Articolo 69 della direttiva 2014/25/UE
      type: object
      required: [anacFormP2,espd]
      additionalProperties: false
      properties:
        anacFormP2:
          $ref: '#/components/schemas/AnacFormP2.17Type'
        espd:
         $ref: 'https://raw.githubusercontent.com/domaltomare/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'           
